version: "3"
services:
  app:
    build:
      context: ./dbmigrate
      dockerfile: Dockerfile
    entrypoint: ["./wait.sh"]
    ports:
      - "8000:8000"

  db:
    platform: linux/x86_64
    image: mysql:8.0.21
    ports:
      - "30000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
