name: Deploy to Cloud Run

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: |-
          gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          cd dbmigrate
          docker build -t gcr.io/${{ secrets.PROJECT_ID }}/api .
          docker push gcr.io/${{ secrets.PROJECT_ID }}/api

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy api \
            --image gcr.io/${{ secrets.PROJECT_ID }}/api\
            --platform managed 
